### ISSUE TITLE
Mix-up of monotype and monospace?

### ISSUE THREAD

**Issue by hartwork** [codingjoe/duolexia#1]
Hi!

This repository caught my attention because the word "monotype" was used here (tag, description, readme). After googling and skip-reading though paper [Good Fonts for Dyslexia](http://dyslexiahelp.umich.edu/sites/default/files/good_fonts_for_dyslexia_study.pdf) I believe that this repository is about a mono*space* font rather than a mono*type* one; I know [Monotype](https://www.monotype.com/) as a big font foundry that [licenses](https://blog.hartwork.org/posts/what-is-wrong-with-monotypes-font-licensing/) typeface Helvetica among others. Am I missing something?

Best, Sebastian

**Comment by codingjoe** [comment]
Thanks @hartwork :)

**Comment by hartwork** [comment]
Unless that was intended: The repo description and repository tags still both say "monotype" rather than "monospace".
